// Icon mapping utility to convert lucide-react icon names to react-native-vector-icons
// This maps icon names from the web version to appropriate Feather icons

export const getIconName = (lucideIconName) => {
    const iconMap = {
        // Navigation & UI
        'Menu': 'menu',
        'MapPin': 'map-pin',
        'ChevronDown': 'chevron-down',
        'ChevronLeft': 'chevron-left',
        'ArrowLeft': 'arrow-left',
        'User': 'user',
        'Bell': 'bell',
        'Search': 'search',
        'Mic': 'mic',
        'Clock': 'clock',
        'Star': 'star',
        'Phone': 'phone',
        'ChevronRight': 'chevron-right',
        'Heart': 'heart',
        'ShoppingBag': 'shopping-bag',
        'Gift': 'gift',
        'ChevronUp': 'chevron-up',
        'Tag': 'tag',
        'Store': 'shopping-cart', // or store if using different set, fallback to shopping-cart

        // Categories
        'Smartphone': 'smartphone',
        'Shirt': 'circle', // Feather doesn't have shirt
        'Pill': 'activity', // Feather doesn't have pill, use 'activity' or 'plus-circle'
        'Zap': 'zap',
        'Home': 'home',
        'Headphones': 'headphones',
        'Trophy': 'award', // Trophy -> award in Feather
        'Scissors': 'scissors',
        'Wrench': 'tool',
        'Car': 'truck', // closest in feather is truck or navigation
        'Book': 'book',
        'Briefcase': 'briefcase',
        'Coffee': 'coffee',
        'Music': 'music',
        'Camera': 'camera',
        'Utensils': 'circle', // fallback
        'Dumbbell': 'activity', // fallback
        'Stethoscope': 'plus-circle', // fallback
        'Building': 'home', // closest
        'GraduationCap': 'book-open', // closest
        'Hammer': 'tool', // closest
        'Truck': 'truck',
        'Baby': 'smile', // closest
        'Tv': 'tv',
        'Sofa': 'square', // fallback
        'Bike': 'circle', // fallback
        'PaintBucket': 'edit-2', // fallback
        'Flower': 'sun', // fallback
        'Leaf': 'wind', // fallback
        'Droplet': 'droplet',

        // Additional icons that might be needed
        'X': 'x',
        'Check': 'check',
        'Edit': 'edit',
        'Trash': 'trash-2',
        'Plus': 'plus',
        'Minus': 'minus',
        'Settings': 'settings',
        'LogOut': 'log-out',
        'HelpCircle': 'help-circle',
        'Info': 'info',
        'Mail': 'mail',
        'MessageCircle': 'message-circle',
        'MessageSquare': 'message-square',
        'Share2': 'share-2',
        'MoreVertical': 'more-vertical',
        'CheckCircle': 'check-circle',
        'SlidersHorizontal': 'sliders',
        'Sliders': 'sliders',
        'AlertCircle': 'alert-circle',
        'ArrowRight': 'arrow-right',
        'Grid': 'grid',
        'Ticket': 'tag',
        'Hash': '#',
        'FileText': 'file-text',
        'File': 'file',
        'TrendingUp': 'trending-up',
        'Package': 'package',
        'Bookmark': 'bookmark',
        'Activity': 'activity',
        'Shield': 'shield',
        'Eye': 'eye',
        'Image': 'image',
        'Calendar': 'calendar',
        'Palette': 'palette',
        'Copy': 'copy',
        'ThumbsUp': 'thumbs-up',
        'Lock': 'lock',
        'PlusCircle': 'plus-circle',
        'CreditCard': 'credit-card',
        'Download': 'download',
        'Upload': 'upload',
        'Tool': 'tool',
        'Wind': 'wind',
        'Box': 'box',
        'Layers': 'layers',
        'Sun': 'sun',
        'Bed': 'home',
        'Smartphone': 'smartphone',
        'Smartphone': 'smartphone',
        'Monitor': 'monitor',
        'Tv': 'tv',
        'MessageCircle': 'message-circle',
        'Music': 'music',
        'Trophy': 'award',
        'Award': 'award',
        'Zap': 'zap',
        'Map': 'map',
        'ArrowRight': 'arrow-right',
        'ArrowLeft': 'arrow-left',
        'ShoppingCart': 'shopping-cart',
        'ShoppingBag': 'shopping-bag',
        'Shirt': 'circle',
        'Clock': 'clock',
        'Compass': 'compass',
        'Target': 'target',
        'Diamond': 'star',
        'Gift': 'gift',
        'Coffee': 'coffee',
        'Utensils': 'circle',
        'Smile': 'smile',
        'Heart': 'heart',
        'Star': 'star',
        'Bell': 'bell',
        'Search': 'search',
        'Trash': 'trash-2',
        'Settings': 'settings',
        'Cpu': 'cpu',
        'Database': 'database',
        'Server': 'server',
        'Wifi': 'wifi',
        'Bluetooth': 'bluetooth',
        'Cast': 'cast',
        'Airplay': 'airplay',
        'HardDrive': 'hard-drive',
        'Disc': 'disc',
        'Film': 'film',
        'Mic': 'mic',
        'Speaker': 'speaker',
        'Volume2': 'volume-2',
        'Headphones': 'headphones',
        'Battery': 'battery',
        'Cloud': 'cloud',
        'Globe': 'globe',
        'Navigation': 'navigation',
        'Navigation2': 'navigation-2',
        'Anchor': 'anchor',
        'Terminal': 'terminal',
        'Code': 'code',
        'Command': 'command',
        'Aperture': 'aperture',
        'Feather': 'feather',
        'Pocket': 'pocket',
        'Inbox': 'inbox',
        'Paperclip': 'paperclip',
        'Share': 'share',
        'Share2': 'share-2',
        'Link': 'link',
        'Link2': 'link-2',
        'ExternalLink': 'external-link',
        'LifeBuoy': 'life-buoy',
        'Tool': 'tool',
        'Wrench': 'tool',
        'Hammer': 'tool',
        'Scissors': 'scissors',
        'PenTool': 'pen-tool',
        'Edit': 'edit',
        'Edit2': 'edit-2',
        'Edit3': 'edit-3',
        'Crop': 'crop',
        'Grid': 'grid',
        'Layout': 'layout',
        'Columns': 'columns',
        'Sidebar': 'sidebar',
        'PieChart': 'pie-chart',
        'BarChart': 'bar-chart',
        'BarChart2': 'bar-chart-2',
        'Activity': 'activity',
        'Eye': 'eye',
        'EyeOff': 'eye-off',
        'Video': 'video',
        'VideoOff': 'video-off',
        'Camera': 'camera',
        'CameraOff': 'camera-off',
        'Smile': 'smile',
        'Meh': 'meh',
        'Frown': 'frown',
        'Flag': 'flag',
        'Play': 'play',
        'Pause': 'pause',
        'Stop': 'stop-circle',
        'FastForward': 'fast-forward',
        'Rewind': 'rewind',
        'SkipBack': 'skip-back',
        'SkipForward': 'skip-forward',
        'Repeat': 'repeat',
        'Shuffle': 'shuffle',
        'RotateCcw': 'rotate-ccw',
        'RotateCw': 'rotate-cw',
        'RefreshCcw': 'refresh-ccw',
        'RefreshCw': 'refresh-cw',
        'Plus': 'plus',
        'PlusCircle': 'plus-circle',
        'PlusSquare': 'plus-square',
        'Minus': 'minus',
        'MinusCircle': 'minus-circle',
        'MinusSquare': 'minus-square',
        'X': 'x',
        'XCircle': 'x-circle',
        'XOctagon': 'x-octagon',
        'XSquare': 'x-square',
        'Check': 'check',
        'CheckCircle': 'check-circle',
        'CheckSquare': 'check-square',
        'AlertCircle': 'alert-circle',
        'AlertOctagon': 'alert-octagon',
        'AlertTriangle': 'alert-triangle',
        'HelpCircle': 'help-circle',
        'Info': 'info',
        'Maximize': 'maximize',
        'Maximize2': 'maximize-2',
        'Minimize': 'minimize',
        'Minimize2': 'minimize-2',
        'ZoomIn': 'zoom-in',
        'ZoomOut': 'zoom-out',
        'Dumbbell': 'award',
        'Baby': 'smile',
        'Building': 'home',
        'GraduationCap': 'book-open',
        'Stethoscope': 'activity',
        'Pharmacy': 'plus-circle',
        'Dentist': 'activity',
        'Bags': 'shopping-bag',
        'Clothes': 'circle',
        'Shoes': 'circle',
        'Jewelry': 'star',
        'Watches': 'clock',
        'Grocery': 'shopping-cart',
        'Supermarket': 'shopping-bag',
        'Bakery': 'coffee',
        'FastFood': 'utensils',
        'Cafe': 'coffee',
        'Salon': 'scissors',
        'Spa': 'droplet',
        'Gym': 'award',
        'Yoga': 'activity',
        'Medical': 'plus-circle',
        'Hardware': 'tool',
        'Plumbing': 'droplet',
        'Electrical': 'zap',
        'CarRepair': 'tool',
        'BikeRepair': 'tool',
        'Property': 'home',
        'RealEstate': 'home',
        'Legal': 'shield',
        'Finance': 'credit-card',
        'Bank': 'credit-card',
        'Insurance': 'shield',
        'Travel': 'map-pin',
        'Event': 'calendar',
        'Wedding': 'heart',
        'Photography': 'camera',
        'Pets': 'heart',
        'Digital': 'monitor',
        'Software': 'code',
        'IT': 'tool',
        'Cleaning': 'sun',
        'PestControl': 'shield',
        'Logistics': 'truck',
        'Courier': 'mail',
        'Cargo': 'package',
        'Warehouse': 'box',
        'Agriculture': 'leaf',
        'Dairy': 'droplet',
        'Meat': 'circle',
        'Fish': 'circle',
    };

    return iconMap[lucideIconName] || 'circle'; // Default fallback to circle
};

